In [36]:
from imblearn.over_sampling import SMOTENC, SMOTE
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from constants import Columns
import numpy as np

In [12]:
DATA_TYPES = {
    Columns.TRANSACTION: np.int8,
    Columns.CUSTOMER_TYPE: "category",
    Columns.SYSTEM_F1: np.int8,
    Columns.SYSTEM_F2: np.int8,
    Columns.SYSTEM_F3: np.int8,
    Columns.SYSTEM_F4: np.int8,
    Columns.SYSTEM_F5: np.int8,
    Columns.ACCOUNT_PAGE: np.int8,
    Columns.ACCOUNT_PAGE_TIME: np.float64,
    Columns.INFO_PAGE: np.int8,
    Columns.INFO_PAGE_TIME: np.float64,
    Columns.PRODUCT_PAGE: np.int16,
    Columns.PRODUCT_PAGE_TIME: np.float64,
    Columns.MONTH: np.int8,
    Columns.WEEKDAY: "bool",
    Columns.SPECIFIC_HOLIDAY: "category",
    Columns.GOOGLE_ANALYTICS_BR: np.float64,
    Columns.GOOGLE_ANALYTICS_ER: np.float64,
    Columns.GOOGLE_ANALYTICS_PV: np.float64,
    Columns.AD_CAMPAIGN_1: np.int8,
    Columns.AD_CAMPAIGN_2: np.int8,
    Columns.AD_CAMPAIGN_3: np.int8,
}

In [13]:
_CSV_FILE = "https://raw.githubusercontent.com/Mlad-en/ML_Challenge/main/Newdata-2.csv"
data = pd.read_csv(_CSV_FILE, dtype=DATA_TYPES)

In [14]:
trgt = data[Columns.TRANSACTION]
data.pop(Columns.TRANSACTION)
preds = data

In [27]:
preds = preds[
[    Columns.CUSTOMER_TYPE,
    Columns.SPECIFIC_HOLIDAY,
    Columns.SYSTEM_F1,
    Columns.SYSTEM_F2,
    Columns.SYSTEM_F3,
    Columns.SYSTEM_F4,
    Columns.SYSTEM_F5,
    Columns.ACCOUNT_PAGE,
    Columns.ACCOUNT_PAGE_TIME,
    Columns.INFO_PAGE,
    Columns.INFO_PAGE_TIME,
    Columns.PRODUCT_PAGE,
    Columns.PRODUCT_PAGE_TIME,
    Columns.MONTH,
    Columns.WEEKDAY,
    Columns.GOOGLE_ANALYTICS_BR,
    Columns.GOOGLE_ANALYTICS_ER,
    Columns.GOOGLE_ANALYTICS_PV,
    Columns.AD_CAMPAIGN_1,
    Columns.AD_CAMPAIGN_2,
    Columns.AD_CAMPAIGN_3]
]

In [37]:
x_train, x_test, y_train, y_test = train_test_split(pd.get_dummies(preds, columns=[Columns.CUSTOMER_TYPE]), trgt)

In [38]:
x_res, y_res = SMOTE().fit_resample(x_train, y_train)

In [39]:
x_res.shape

(15516, 23)

In [41]:
pd.get_dummies(preds, columns=[Columns.CUSTOMER_TYPE])

,SpecificHoliday,SystemF1,SystemF2,SystemF3,SystemF4,SystemF5,Account_Page,Account_Page_Time,Info_Page,Info_Page_Time,...,Weekday,GoogleAnalytics_BR,GoogleAnalytics_ER,GoogleAnalytics_PV,Ad_Campaign_1,Ad_Campaign2,Ad_Campaign3,Customer_Type_New_Customer,Customer_Type_Other,Customer_Type_Returning_Customer
0,0,1,2,7,10,2,0,0.000000,0,0.0,...,True,0.200000,0.200000,0.000000,0,0,0,0,0,1
1,0,2,2,3,2,3,10,147.458333,4,216.5,...,True,0.000000,0.010046,0.000000,0,0,0,0,0,1
2,0,2,2,1,2,1,0,0.000000,0,0.0,...,True,0.000000,0.033333,0.000000,0,0,0,1,0,0
3,0.8,2,2,2,6,1,0,0.000000,0,0.0,...,True,0.011765,0.052941,0.000000,0,0,0,0,0,1
4,0,2,2,4,10,3,0,0.000000,2,45.0,...,True,0.015385,0.046154,0.000000,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12200,0,1,1,6,5,5,4,68.666667,0,0.0,...,True,0.000000,0.004444,9.253162,0,0,0,1,0,0
12201,0,3,2,1,10,3,7,86.277778,2,21.0,...,False,0.003571,0.021528,25.765986,0,0,0,0,0,1
12202,0,3,2,1,7,2,0,0.000000,0,0.0,...,False,0.000000,0.050000,0.000000,0,0,0,0,0,1
12203,0,2,2,6,5,4,4,102.200000,0,0.0,...,True,0.000000,0.016667,0.000000,0,0,0,1,0,0
12204,0,3,2,7,11,1,3,49.750000,0,0.0,...,True,0.000000,0.003333,0.000000,0,0,0,1,0,0